### PR TITLE
Feature #5945

### PR DESCRIPTION
**Pull request by pascalandermatt**
Added Retina Favicon.

Issue: iPhone "Add to Home" Black Background

### CODE REVIEW

**Comment by diegosteiner** [comment]
Looks good, but we don't want old/dead code anymore. So please remove the files and lines that aren't used anymore. If we need them one day, we can look it up in the commit-history.

**Comment by lukaselmer** [comment]
seems like it didn't really work?
image

**Comment by cyrilkyburz** [comment]
The master branch was last updated 25 days ago. We should deploy a new release.

**Comment by lukaselmer** [comment]
@cyrilkyburz it's already merged into develop and thus published under https://new.renuo.ch/ ;)

**Comment by lukaselmer** [comment]
however, it's fixed in #161

**Comment by cyrilkyburz** [comment]
I searched for a develop branch but I couldn't find one. Now it's clear. (new.renuo.ch)

**Comment by lukaselmer** [comment]
yes, I just started documenting it ;)

image

**Pull request merged**
